### ISSUE TITLE
AH scan showing pets that have already been obtained.

### ISSUE THREAD

**Issue by penguinsane** [Phanx/PetMarket#2]
First, thanks for addressing that other error. PetMarket finally works with TSM for me!

I installed Ace3, LibPetJournal-2.0, and updated PetMarket from github. Now when I click "scan auction house", it lists pets I already have instead of just filtering to unowned ones like it originally did.

Example: http://puu.sh/ktWlA/23b6fc6d52.jpg (I have every pet listed on that screen)

(My UI doesn't have the window textured, it's an issue with my UI and not the addon though, I believe.)

**Comment by chodyo** [comment]
#3 should provide the fix this issue is referring to.

**Comment by Phanx** [comment]
Weird, apparently I wasn't auto-subscribed to my own project? Anyway, I'd actually fixed this ages ago, but apparently am also bad at committing things in a timely manner. However, I've been working on the cleanup branch, so I'll go ahead and merge your pull request into the master branch.

**Comment by chodyo** [comment]
Cool! Thanks for all your work. I'm glad I got to dig in and learn a bit about wow addons with your project.
